language: bash

sudo: required

services: [docker]

script:
  - docker run -v $(pwd):$(pwd) -w $(pwd) snapcore/snapcraft:stable sh -c "apt update && snapcraft"
  - sudo apt update
  - sudo apt install --yes snapd
  - sudo snap install *.snap --classic --dangerous
  - sudo pip install -U pytest
  - pwd
  - ps -ef
  - ls -l
  - ./tests/smoke-test.sh
  - (cd tests; pytest -s verify-branches.py)
  - (cd tests; pytest -s test-addons.py)
  - sudo microk8s.reset
  - sudo snap remove microk8s
