#!/usr/bin/env bash
set -eu

snapctl stop ${SNAP_NAME}.daemon-kubelet 2>&1 || true
snapctl stop ${SNAP_NAME}.daemon-docker 2>&1 || true
(cat /proc/mounts | grep ${SNAP_COMMON}/pods | cut -d ' ' -f 2 | xargs umount) || true
(cat /proc/mounts | grep ${SNAP_COMMON}/var/lib/containerd | cut -d ' ' -f 2 | xargs umount) || true
(cat /proc/mounts | grep ${SNAP_COMMON}/var/run/containerd | cut -d ' ' -f 2 | xargs umount) || true
